title: Simon Lederhilger
logo: /assets/img/simon.jpg
description: My academic and personal webpage
url: "https://lederhilger.github.io"
baseurl: ""
email: "simonled@uio.no"

profile_links:
  - label: GitHub
    url: https://github.com/lederhilger
    icon: /assets/img/icons/invertocat.svg
    dark_icon: /assets/img/icons/dark_invertocat.svg
  - label: GitLab
    url: https://gitlab.com/lederhilger
    icon: /assets/img/icons/gitlab.svg
    dark_icon: /assets/img/icons/dark_gitlab.svg
  - label: LinkedIn
    url: https://linkedin.com/in/simonled
    icon: /assets/img/icons/in.svg
    dark_icon: /assets/img/icons/dark_in.svg

theme: jekyll-theme-minimal

collections:
  entries:
    output: true
    permalink: /weblog/:name/
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
      
  - scope:
      path: ""
      type: entries
    values:
      layout: default

  - scope:
      path: "_projects/academic"
      type: projects
    values:
      project_kind: academic

  - scope:
      path: "_projects/personal"
      type: projects
    values:
      project_kind: personal